import { Country } from '@/types/country';

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'af', flagUrl: 'https://flagcdn.com/af.png' },
  { name: 'Albania', code: 'al', flagUrl: 'https://flagcdn.com/al.png' },
  { name: 'Algeria', code: 'dz', flagUrl: 'https://flagcdn.com/dz.png' },
  { name: 'Andorra', code: 'ad', flagUrl: 'https://flagcdn.com/ad.png' },
  { name: 'Angola', code: 'ao', flagUrl: 'https://flagcdn.com/ao.png' },
  { name: 'Antigua and Barbuda', code: 'ag', flagUrl: 'https://flagcdn.com/ag.png' },
  { name: 'Argentina', code: 'ar', flagUrl: 'https://flagcdn.com/ar.png' },
  { name: 'Armenia', code: 'am', flagUrl: 'https://flagcdn.com/am.png' },
  { name: 'Australia', code: 'au', flagUrl: 'https://flagcdn.com/au.png' },
  { name: 'Austria', code: 'at', flagUrl: 'https://flagcdn.com/at.png' },
  { name: 'Azerbaijan', code: 'az', flagUrl: 'https://flagcdn.com/az.png' },
  { name: 'Bahamas', code: 'bs', flagUrl: 'https://flagcdn.com/bs.png' },
  { name: 'Bahrain', code: 'bh', flagUrl: 'https://flagcdn.com/bh.png' },
  { name: 'Bangladesh', code: 'bd', flagUrl: 'https://flagcdn.com/bd.png' },
  { name: 'Barbados', code: 'bb', flagUrl: 'https://flagcdn.com/bb.png' },
  { name: 'Belarus', code: 'by', flagUrl: 'https://flagcdn.com/by.png' },
  { name: 'Belgium', code: 'be', flagUrl: 'https://flagcdn.com/be.png' },
  { name: 'Belize', code: 'bz', flagUrl: 'https://flagcdn.com/bz.png' },
  { name: 'Benin', code: 'bj', flagUrl: 'https://flagcdn.com/bj.png' },
  { name: 'Bhutan', code: 'bt', flagUrl: 'https://flagcdn.com/bt.png' },
  { name: 'Bolivia', code: 'bo', flagUrl: 'https://flagcdn.com/bo.png' },
  { name: 'Bosnia and Herzegovina', code: 'ba', flagUrl: 'https://flagcdn.com/ba.png' },
  { name: 'Botswana', code: 'bw', flagUrl: 'https://flagcdn.com/bw.png' },
  { name: 'Brazil', code: 'br', flagUrl: 'https://flagcdn.com/br.png' },
  { name: 'Brunei', code: 'bn', flagUrl: 'https://flagcdn.com/bn.png' },
  { name: 'Bulgaria', code: 'bg', flagUrl: 'https://flagcdn.com/bg.png' },
  { name: 'Burkina Faso', code: 'bf', flagUrl: 'https://flagcdn.com/bf.png' },
  { name: 'Burundi', code: 'bi', flagUrl: 'https://flagcdn.com/bi.png' },
  { name: 'Cambodia', code: 'kh', flagUrl: 'https://flagcdn.com/kh.png' },
  { name: 'Cameroon', code: 'cm', flagUrl: 'https://flagcdn.com/cm.png' },
  { name: 'Canada', code: 'ca', flagUrl: 'https://flagcdn.com/ca.png' },
  { name: 'Cape Verde', code: 'cv', flagUrl: 'https://flagcdn.com/cv.png' },
  { name: 'Central African Republic', code: 'cf', flagUrl: 'https://flagcdn.com/cf.png' },
  { name: 'Chad', code: 'td', flagUrl: 'https://flagcdn.com/td.png' },
  { name: 'Chile', code: 'cl', flagUrl: 'https://flagcdn.com/cl.png' },
  { name: 'China', code: 'cn', flagUrl: 'https://flagcdn.com/cn.png' },
  { name: 'Colombia', code: 'co', flagUrl: 'https://flagcdn.com/co.png' },
  { name: 'Comoros', code: 'km', flagUrl: 'https://flagcdn.com/km.png' },
  { name: 'Congo (Congo-Brazzaville)', code: 'cg', flagUrl: 'https://flagcdn.com/cg.png' },
  { name: 'Costa Rica', code: 'cr', flagUrl: 'https://flagcdn.com/cr.png' },
  { name: 'Croatia', code: 'hr', flagUrl: 'https://flagcdn.com/hr.png' },
  { name: 'Cuba', code: 'cu', flagUrl: 'https://flagcdn.com/cu.png' },
  { name: 'Cyprus', code: 'cy', flagUrl: 'https://flagcdn.com/cy.png' },
  { name: 'Czech Republic', code: 'cz', flagUrl: 'https://flagcdn.com/cz.png' },
  { name: 'Denmark', code: 'dk', flagUrl: 'https://flagcdn.com/dk.png' },
  { name: 'Djibouti', code: 'dj', flagUrl: 'https://flagcdn.com/dj.png' },
  { name: 'Dominica', code: 'dm', flagUrl: 'https://flagcdn.com/dm.png' },
  { name: 'Dominican Republic', code: 'do', flagUrl: 'https://flagcdn.com/do.png' },
  { name: 'East Timor', code: 'tl', flagUrl: 'https://flagcdn.com/tl.png' },
  { name: 'Ecuador', code: 'ec', flagUrl: 'https://flagcdn.com/ec.png' },
  { name: 'Egypt', code: 'eg', flagUrl: 'https://flagcdn.com/eg.png' },
  { name: 'El Salvador', code: 'sv', flagUrl: 'https://flagcdn.com/sv.png' },
  { name: 'Equatorial Guinea', code: 'gq', flagUrl: 'https://flagcdn.com/gq.png' },
  { name: 'Eritrea', code: 'er', flagUrl: 'https://flagcdn.com/er.png' },
  { name: 'Estonia', code: 'ee', flagUrl: 'https://flagcdn.com/ee.png' },
  { name: 'Eswatini', code: 'sz', flagUrl: 'https://flagcdn.com/sz.png' },
  { name: 'Ethiopia', code: 'et', flagUrl: 'https://flagcdn.com/et.png' },
  { name: 'Fiji', code: 'fj', flagUrl: 'https://flagcdn.com/fj.png' },
  { name: 'Finland', code: 'fi', flagUrl: 'https://flagcdn.com/fi.png' },
  { name: 'France', code: 'fr', flagUrl: 'https://flagcdn.com/fr.png' },
  { name: 'Gabon', code: 'ga', flagUrl: 'https://flagcdn.com/ga.png' },
  { name: 'Gambia', code: 'gm', flagUrl: 'https://flagcdn.com/gm.png' },
  { name: 'Georgia', code: 'ge', flagUrl: 'https://flagcdn.com/ge.png' },
  { name: 'Germany', code: 'de', flagUrl: 'https://flagcdn.com/de.png' },
  { name: 'Ghana', code: 'gh', flagUrl: 'https://flagcdn.com/gh.png' },
  { name: 'Greece', code: 'gr', flagUrl: 'https://flagcdn.com/gr.png' },
  { name: 'Grenada', code: 'gd', flagUrl: 'https://flagcdn.com/gd.png' },
  { name: 'Guatemala', code: 'gt', flagUrl: 'https://flagcdn.com/gt.png' },
  { name: 'Guinea', code: 'gn', flagUrl: 'https://flagcdn.com/gn.png' },
  { name: 'Guinea-Bissau', code: 'gw', flagUrl: 'https://flagcdn.com/gw.png' },
  { name: 'Guyana', code: 'gy', flagUrl: 'https://flagcdn.com/gy.png' },
  { name: 'Haiti', code: 'ht', flagUrl: 'https://flagcdn.com/ht.png' },
  { name: 'Honduras', code: 'hn', flagUrl: 'https://flagcdn.com/hn.png' },
  { name: 'Hungary', code: 'hu', flagUrl: 'https://flagcdn.com/hu.png' },
  { name: 'Iceland', code: 'is', flagUrl: 'https://flagcdn.com/is.png' },
  { name: 'India', code: 'in', flagUrl: 'https://flagcdn.com/in.png' },
  { name: 'Indonesia', code: 'id', flagUrl: 'https://flagcdn.com/id.png' },
  { name: 'Iran', code: 'ir', flagUrl: 'https://flagcdn.com/ir.png' },
  { name: 'Iraq', code: 'iq', flagUrl: 'https://flagcdn.com/iq.png' },
  { name: 'Ireland', code: 'ie', flagUrl: 'https://flagcdn.com/ie.png' },
  { name: 'Israel', code: 'il', flagUrl: 'https://flagcdn.com/il.png' },
  { name: 'Italy', code: 'it', flagUrl: 'https://flagcdn.com/it.png' },
  { name: 'Ivory Coast', code: 'ci', flagUrl: 'https://flagcdn.com/ci.png' },
  { name: 'Jamaica', code: 'jm', flagUrl: 'https://flagcdn.com/jm.png' },
  { name: 'Japan', code: 'jp', flagUrl: 'https://flagcdn.com/jp.png' },
  { name: 'Jordan', code: 'jo', flagUrl: 'https://flagcdn.com/jo.png' },
  { name: 'Kazakhstan', code: 'kz', flagUrl: 'https://flagcdn.com/kz.png' },
  { name: 'Kenya', code: 'ke', flagUrl: 'https://flagcdn.com/ke.png' },
  { name: 'Kiribati', code: 'ki', flagUrl: 'https://flagcdn.com/ki.png' },
  { name: 'Kosovo', code: 'xk', flagUrl: 'https://flagcdn.com/xk.png' },
  { name: 'Kuwait', code: 'kw', flagUrl: 'https://flagcdn.com/kw.png' },
  { name: 'Kyrgyzstan', code: 'kg', flagUrl: 'https://flagcdn.com/kg.png' },
  { name: 'Laos', code: 'la', flagUrl: 'https://flagcdn.com/la.png' },
  { name: 'Latvia', code: 'lv', flagUrl: 'https://flagcdn.com/lv.png' },
  { name: 'Lebanon', code: 'lb', flagUrl: 'https://flagcdn.com/lb.png' },
  { name: 'Lesotho', code: 'ls', flagUrl: 'https://flagcdn.com/ls.png' },
  { name: 'Liberia', code: 'lr', flagUrl: 'https://flagcdn.com/lr.png' },
  { name: 'Libya', code: 'ly', flagUrl: 'https://flagcdn.com/ly.png' },
  { name: 'Liechtenstein', code: 'li', flagUrl: 'https://flagcdn.com/li.png' },
  { name: 'Lithuania', code: 'lt', flagUrl: 'https://flagcdn.com/lt.png' },
  { name: 'Luxembourg', code: 'lu', flagUrl: 'https://flagcdn.com/lu.png' },
  { name: 'Madagascar', code: 'mg', flagUrl: 'https://flagcdn.com/mg.png' },
  { name: 'Malawi', code: 'mw', flagUrl: 'https://flagcdn.com/mw.png' },
  { name: 'Malaysia', code: 'my', flagUrl: 'https://flagcdn.com/my.png' },
  { name: 'Maldives', code: 'mv', flagUrl: 'https://flagcdn.com/mv.png' },
  { name: 'Mali', code: 'ml', flagUrl: 'https://flagcdn.com/ml.png' },
  { name: 'Malta', code: 'mt', flagUrl: 'https://flagcdn.com/mt.png' },
  { name: 'Marshall Islands', code: 'mh', flagUrl: 'https://flagcdn.com/mh.png' },
  { name: 'Mauritania', code: 'mr', flagUrl: 'https://flagcdn.com/mr.png' },
  { name: 'Mauritius', code: 'mu', flagUrl: 'https://flagcdn.com/mu.png' },
  { name: 'Mexico', code: 'mx', flagUrl: 'https://flagcdn.com/mx.png' },
  { name: 'Micronesia', code: 'fm', flagUrl: 'https://flagcdn.com/fm.png' },
  { name: 'Moldova', code: 'md', flagUrl: 'https://flagcdn.com/md.png' },
  { name: 'Monaco', code: 'mc', flagUrl: 'https://flagcdn.com/mc.png' },
  { name: 'Mongolia', code: 'mn', flagUrl: 'https://flagcdn.com/mn.png' },
  { name: 'Montenegro', code: 'me', flagUrl: 'https://flagcdn.com/me.png' },
  { name: 'Morocco', code: 'ma', flagUrl: 'https://flagcdn.com/ma.png' },
  { name: 'Mozambique', code: 'mz', flagUrl: 'https://flagcdn.com/mz.png' },
  { name: 'Myanmar', code: 'mm', flagUrl: 'https://flagcdn.com/mm.png' },
  { name: 'Namibia', code: 'na', flagUrl: 'https://flagcdn.com/na.png' },
  { name: 'Nauru', code: 'nr', flagUrl: 'https://flagcdn.com/nr.png' },
  { name: 'Nepal', code: 'np', flagUrl: 'https://flagcdn.com/np.png' },
  { name: 'Netherlands', code: 'nl', flagUrl: 'https://flagcdn.com/nl.png' },
  { name: 'New Zealand', code: 'nz', flagUrl: 'https://flagcdn.com/nz.png' },
  { name: 'Nicaragua', code: 'ni', flagUrl: 'https://flagcdn.com/ni.png' },
  { name: 'Niger', code: 'ne', flagUrl: 'https://flagcdn.com/ne.png' },
  { name: 'Nigeria', code: 'ng', flagUrl: 'https://flagcdn.com/ng.png' },
  { name: 'North Korea', code: 'kp', flagUrl: 'https://flagcdn.com/kp.png' },
  { name: 'North Macedonia', code: 'mk', flagUrl: 'https://flagcdn.com/mk.png' },
  { name: 'Norway', code: 'no', flagUrl: 'https://flagcdn.com/no.png' },
  { name: 'Oman', code: 'om', flagUrl: 'https://flagcdn.com/om.png' },
  { name: 'Pakistan', code: 'pk', flagUrl: 'https://flagcdn.com/pk.png' },
  { name: 'Palau', code: 'pw', flagUrl: 'https://flagcdn.com/pw.png' },
  { name: 'Palestine', code: 'ps', flagUrl: 'https://flagcdn.com/ps.png' },
  { name: 'Panama', code: 'pa', flagUrl: 'https://flagcdn.com/pa.png' },
  { name: 'Papua New Guinea', code: 'pg', flagUrl: 'https://flagcdn.com/pg.png' },
  { name: 'Paraguay', code: 'py', flagUrl: 'https://flagcdn.com/py.png' },
  { name: 'Peru', code: 'pe', flagUrl: 'https://flagcdn.com/pe.png' },
  { name: 'Philippines', code: 'ph', flagUrl: 'https://flagcdn.com/ph.png' },
  { name: 'Poland', code: 'pl', flagUrl: 'https://flagcdn.com/pl.png' },
  { name: 'Portugal', code: 'pt', flagUrl: 'https://flagcdn.com/pt.png' },
  { name: 'Qatar', code: 'qa', flagUrl: 'https://flagcdn.com/qa.png' },
  { name: 'Romania', code: 'ro', flagUrl: 'https://flagcdn.com/ro.png' },
  { name: 'Russia', code: 'ru', flagUrl: 'https://flagcdn.com/ru.png' },
  { name: 'Rwanda', code: 'rw', flagUrl: 'https://flagcdn.com/rw.png' },
  { name: 'Saint Kitts and Nevis', code: 'kn', flagUrl: 'https://flagcdn.com/kn.png' },
  { name: 'Saint Lucia', code: 'lc', flagUrl: 'https://flagcdn.com/lc.png' },
  { name: 'Saint Vincent and the Grenadines', code: 'vc', flagUrl: 'https://flagcdn.com/vc.png' },
  { name: 'Samoa', code: 'ws', flagUrl: 'https://flagcdn.com/ws.png' },
  { name: 'San Marino', code: 'sm', flagUrl: 'https://flagcdn.com/sm.png' },
  { name: 'Sao Tome and Principe', code: 'st', flagUrl: 'https://flagcdn.com/st.png' },
  { name: 'Saudi Arabia', code: 'sa', flagUrl: 'https://flagcdn.com/sa.png' },
  { name: 'Senegal', code: 'sn', flagUrl: 'https://flagcdn.com/sn.png' },
  { name: 'Serbia', code: 'rs', flagUrl: 'https://flagcdn.com/rs.png' },
  { name: 'Seychelles', code: 'sc', flagUrl: 'https://flagcdn.com/sc.png' },
  { name: 'Sierra Leone', code: 'sl', flagUrl: 'https://flagcdn.com/sl.png' },
  { name: 'Singapore', code: 'sg', flagUrl: 'https://flagcdn.com/sg.png' },
  { name: 'Slovakia', code: 'sk', flagUrl: 'https://flagcdn.com/sk.png' },
  { name: 'Slovenia', code: 'si', flagUrl: 'https://flagcdn.com/si.png' },
  { name: 'Solomon Islands', code: 'sb', flagUrl: 'https://flagcdn.com/sb.png' },
  { name: 'Somalia', code: 'so', flagUrl: 'https://flagcdn.com/so.png' },
  { name: 'South Africa', code: 'za', flagUrl: 'https://flagcdn.com/za.png' },
  { name: 'South Korea', code: 'kr', flagUrl: 'https://flagcdn.com/kr.png' },
  { name: 'South Sudan', code: 'ss', flagUrl: 'https://flagcdn.com/ss.png' },
  { name: 'Spain', code: 'es', flagUrl: 'https://flagcdn.com/es.png' },
  { name: 'Sri Lanka', code: 'lk', flagUrl: 'https://flagcdn.com/lk.png' },
  { name: 'Sudan', code: 'sd', flagUrl: 'https://flagcdn.com/sd.png' },
  { name: 'Suriname', code: 'sr', flagUrl: 'https://flagcdn.com/sr.png' },
  { name: 'Sweden', code: 'se', flagUrl: 'https://flagcdn.com/se.png' },
  { name: 'Switzerland', code: 'ch', flagUrl: 'https://flagcdn.com/ch.png' },
  { name: 'Syria', code: 'sy', flagUrl: 'https://flagcdn.com/sy.png' },
  { name: 'Taiwan', code: 'tw', flagUrl: 'https://flagcdn.com/tw.png' },
  { name: 'Tajikistan', code: 'tj', flagUrl: 'https://flagcdn.com/tj.png' },
  { name: 'Tanzania', code: 'tz', flagUrl: 'https://flagcdn.com/tz.png' },
  { name: 'Thailand', code: 'th', flagUrl: 'https://flagcdn.com/th.png' },
  { name: 'Togo', code: 'tg', flagUrl: 'https://flagcdn.com/tg.png' },
  { name: 'Tonga', code: 'to', flagUrl: 'https://flagcdn.com/to.png' },
  { name: 'Trinidad and Tobago', code: 'tt', flagUrl: 'https://flagcdn.com/tt.png' },
  { name: 'Tunisia', code: 'tn', flagUrl: 'https://flagcdn.com/tn.png' },
  { name: 'Turkey', code: 'tr', flagUrl: 'https://flagcdn.com/tr.png' },
  { name: 'Turkmenistan', code: 'tm', flagUrl: 'https://flagcdn.com/tm.png' },
  { name: 'Tuvalu', code: 'tv', flagUrl: 'https://flagcdn.com/tv.png' },
  { name: 'Uganda', code: 'ug', flagUrl: 'https://flagcdn.com/ug.png' },
  { name: 'Ukraine', code: 'ua', flagUrl: 'https://flagcdn.com/ua.png' },
  { name: 'United Arab Emirates', code: 'ae', flagUrl: 'https://flagcdn.com/ae.png' },
  { name: 'United Kingdom', code: 'gb', flagUrl: 'https://flagcdn.com/gb.png' },
  { name: 'United States', code: 'us', flagUrl: 'https://flagcdn.com/us.png' },
  { name: 'Uruguay', code: 'uy', flagUrl: 'https://flagcdn.com/uy.png' },
  { name: 'Uzbekistan', code: 'uz', flagUrl: 'https://flagcdn.com/uz.png' },
  { name: 'Vanuatu', code: 'vu', flagUrl: 'https://flagcdn.com/vu.png' },
  { name: 'Vatican City', code: 'va', flagUrl: 'https://flagcdn.com/va.png' },
  { name: 'Venezuela', code: 've', flagUrl: 'https://flagcdn.com/ve.png' },
  { name: 'Vietnam', code: 'vn', flagUrl: 'https://flagcdn.com/vn.png' },
  { name: 'Yemen', code: 'ye', flagUrl: 'https://flagcdn.com/ye.png' },
  { name: 'Zambia', code: 'zm', flagUrl: 'https://flagcdn.com/zm.png' },
  { name: 'Zimbabwe', code: 'zw', flagUrl: 'https://flagcdn.com/zw.png' },
];
